apiVersion: apps/v1
kind: Deployment
metadata:
  name: comodes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comodes
  template:
    metadata:
      labels:
        app: comodes
    spec:
      containers:
      - image: okteto.dev/comodes:latest
        name: comodes
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f3467655-7e4e-492a-b251-4dd8e524efc5"
        - name: Vless_Path
          value: "/vlbeauty22"
        - name: Vmess_UUID
          value: "f3467655-7e4e-492a-b251-4dd8e524efc5"
        - name: Vmess_Path
          value: "/vmbeauty23"
        - name: Share_Path
          value: "/v2link"
